halo-dev/plugin-s3

- README.md
增加oracle cloud的配置，实测可以上传。
官方文档地址：https://docs.oracle.com/en-us/iaas/Content/Object/Tasks/s3compatibleapi.htm
`Path Style`和`Virtual Hosted Style`均可以配置，并测试成功。
推荐使用`Virtual Hosted Style`方式：
entrypoint: compat.objectstorage.{region}.oraclecloud.com
将`{region}`替换为上图中`区域`的值
绑定域名留空
`Access Key`和`Access Secret` 在用户设置里面生成`客户秘钥`
```release-note
None
```
> add oracle cloud configuration guide in README

- src/main/java/run/halo/s3os/FileNameUtils.java
- src/main/java/run/halo/s3os/S3OsAttachmentHandler.java
Fixes https://github.com/halo-dev/halo/issues/3337
不更新依赖了，直接复制了FileNameUtils
在有image.png的情况下再同时粘贴两张截图，期望两张都能被上传且被自动重命名。
```release-note
文件存在时自动重命名
```
> perf: auto rename attachment if it exists

- src/main/java/run/halo/s3os/S3OsAttachmentHandler.java
Share URL mechanism was provided in https://github.com/halo-sigs/plugin-s3/pull/35, and I set the TTL of the URL with 5 mins incorrectly.
```release-note
None
```
> Fix incorrect setting on TTL of share URL

- src/main/java/run/halo/s3os/S3OsAttachmentHandler.java
Fixes https://github.com/halo-sigs/plugin-s3/issues/40
```release-note
None
```
> Fix url space error

- src/main/java/run/halo/s3os/S3OsAttachmentHandler.java
See https://github.com/halo-sigs/plugin-s3/issues/56 for more.
This PR skips permalink resolution while the object key is missing. So that the default handler will resolve permalink from annotation `storage.halo.run/external-link`
Fixes https://github.com/halo-sigs/plugin-s3/issues/56
```release-note
解决导入 Halo 1.x 附件后出现“Cannot obtain object key from attachment attachment-xyz”的问题
```
> Fallback to default handler for backward compatibility

- src/main/java/run/halo/s3os/FileNameUtils.java
- src/main/java/run/halo/s3os/S3OsAttachmentHandler.java
- src/main/java/run/halo/s3os/S3OsProperties.java
- src/main/resources/extensions/policy-template-s3os.yaml
图片等文件外链往往需要呈现给用户，由于大部分时候我们都是随手创建的新文件或从别处复制粘贴，文件名会如同`无标题.png`等，上传后按照默认策略也会如同`无标题-qiks.png`等，既不美观也会给用户造成困扰。此功能可以在上传文件时将文件名自动替换为UUID、日期、随机字符串等格式。
```release-note
增加自动随机重命名文件可选功能
```
> feat: automatic random file renaming optional feature

- src/main/resources/extensions/policy-template-s3os.yaml
Fixes #67 
```release-note
优化`Access Key`相关的描述，减少误解
```
> chore: Optimize access_key description

- build.gradle
Halo modified the [class loading order](https://github.com/halo-dev/halo/pull/4663) of plugins in 2.10.x to P (Plugin) D (Dependencies) A (Application), resulting in a LinkageError when the current plugin is actually run.
```java
java.lang.LinkageError: loader constraint violation: when resolving method 'reactor.core.publisher.Flux reactor.core.publisher.Mono.thenMany(org.reactivestreams.Publisher)' the class loader org.pf4j.PluginClassLoader @5da2e534 of the current class, run/halo/s3os/S3OsAttachmentHandler, and the class loader org.springframework.boot.loader.LaunchedURLClassLoader @87aac27 for the method's defining class, reactor/core/publisher/Mono, have different Class objects for the type org/reactivestreams/Publisher used in the signature (run.halo.s3os.S3OsAttachmentHandler is in …
```
> Exclude reactive-streams module for runtime classpath

- src/main/java/run/halo/s3os/S3OsAttachmentHandler.java
- src/main/java/run/halo/s3os/S3OsProperties.java
- src/main/java/run/halo/s3os/UrlUtils.java
- src/main/resources/extensions/policy-template-s3os.yaml
- src/test/java/run/halo/s3os/UrlUtilsTest.java
增加网址后缀功能
此功能在文件上传和关联文件均生效
Fix #77 
Fix #68 
```release-note
增加给指定类型的文件加上特定的网址后缀功能
```
> feat: add URL suffix to files of specified type

- src/main/java/run/halo/s3os/S3LinkServiceImpl.java
- src/main/java/run/halo/s3os/S3OsAttachmentHandler.java
fixes https://github.com/halo-dev/plugin-s3/issues/90
请测试 `上传时重命名文件方式` 选项为**非**保留原文件名时，是否能正常关联s3文件
```release-note
当上传时文件重命名功能开启时关联S3文件错误
```
> fix: s3 link error when filename renaming enable

- build.gradle
- src/main/java/run/halo/s3os/S3OsAttachmentHandler.java
```release-note
修复无日志输出的问题
```
fixes #100 
测试上传，关联，删除，解除关联 4种操作的日志
```
---上传---
2023-11-27T22:39:22.139+08:00  INFO 7 --- [oundedElastic-5] run.halo.s3os.S3OsAttachmentHandler      : operation: createMultipartUpload, result: CreateMultipartUploadResponse(Bucket=test-1305034426, Key=test/image-pjcl.png, UploadId=17010959629c897f8b8c1a592b0efe300de867a1ea3e891cf04b4f95c6986470a0f30195be)
2023-11-27T22:39:22.391+08:00  INFO 7 --- [oundedElastic-5] run.halo.s3os.S3OsAttachmentHandler      : operation: uploadPart, result: UploadPartResponse(ETag="aa84eea735192b49552fa5bf3df317fa")
2023-11-27T22:39:22.547+08:00  INFO 7 --- [oundedElastic-5] run.halo.s3os.S3OsAttachmentHandler      : operation: completeUpload, result: CompleteMultipartUploadResponse(Location=http://test-1305034426.cos.ap-guangzho …
```
> fix: log cannot be output and log information error

- src/main/java/run/halo/s3os/S3ExceptionHandler.java
- src/main/java/run/halo/s3os/S3LinkServiceImpl.java
- src/main/java/run/halo/s3os/S3OsAttachmentHandler.java
- src/main/java/run/halo/s3os/S3UnlinkServiceImpl.java
```release-note
友好地提示异常信息
```
fixes https://github.com/halo-dev/plugin-s3/issues/105
验证方法：
1. ak/sk乱输，发生接收到403状态码（接收错误状态码）
2. endpoint网址改成不存在的，如.com改成.comaaa（未知主机）
3. endpoint端口改成没监听的（超时）
> perf: improve more friendly exception messages

- console/package.json
- console/pnpm-lock.yaml
- console/src/index.ts
- src/main/resources/plugin.yaml
将 S3 关联页面放置在左侧菜单。
Note: 此特性需要运行在 Halo 2.12 才生效，所以此 PR 同时修改了 requires。
```release-note
将 S3 关联页面放置在左侧菜单。
```
> refactor: place the entry for the S3 link page in the side menu

- console/src/views/S3Link.vue
```release-note
修复关联S3文件页面中 page size 下拉框样式缺失的问题
```
Before:
After:
> fix: missing page size selector style

- src/main/resources/extensions/s3os-role-template.yaml
```release-note
None
```
入口已从插件设置页移除，移除依赖插件查看权限
> chore: remove plugin view permissions from S3 Link permission dependency

- src/main/resources/extensions/policy-template-s3os.yaml
> chore: correcting incorrect policy template field help text

- src/main/java/run/halo/s3os/PlaceholderReplacer.java
```release-note
修复重命名模板中 millisecond 没有被格式化3位数的问题
```
> fix: Correct the formatting of Milliseconds to be a 3-digit number

- src/main/resources/extensions/policy-template-s3os.yaml
在 Halo 完成动态数据的 i18n 之前，使用中文描述存储策略名称。
```release-note
修改存储策略名称为中文显示。
```
> chore: rename displayName to S3 对象存储

- build.gradle
- src/main/java/run/halo/s3os/LinkRequest.java
- src/main/java/run/halo/s3os/S3LinkController.java
- src/main/java/run/halo/s3os/S3LinkService.java
- src/main/java/run/halo/s3os/S3LinkServiceImpl.java
- src/main/resources/plugin.yaml
```release-note
使用索引优化“关联S3文件”接口
```
> perf: optimize s3link interfaces using index mechanisms

- src/main/java/run/halo/s3os/FilePathUtils.java
```release-note
修复上传目录中 ${origin-filename} 占位符被错误替换为空字符串的问题
```
> Fix original file name being incorrectly replaced

- src/main/resources/extensions/settings.yaml
使用占位组件在设置页面展示信息并不恰当，并且此项目作为存储插件的 Example 工程易误导其他开发者。
调整为利用 FormKit `el` 特性实现。
问题背景：https://github.com/halo-dev/halo/issues/5802
**Preview - old**
**Preview - new**
```release-note
优化调整提示的提示
```
> improve usage tips in settings page

- console/src/views/S3Link.vue
```release-note
修复 S3 关联中策略选择器太短的问题
```
fixes #141
> Fix: Correct policy selector styling issue

- console/src/controller/s-3-link-controller/getApisS3OsHaloRunV1Alpha1ObjectsByPolicyName.ts
- console/src/utils/request.ts
- console/src/views/S3Link.vue
- src/main/java/run/halo/s3os/S3LinkController.java
- src/main/java/run/halo/s3os/S3LinkService.java
- src/main/java/run/halo/s3os/S3LinkServiceImpl.java
```release-note
在 S3关联 中支持文件名前缀搜索
```
fixes https://github.com/halo-dev/plugin-s3/issues/142
> faet: Add file prefix search function in s3link

- src/main/java/run/halo/s3os/S3LinkServiceImpl.java
```release-note
None
```
传递unsorted以支持Halo 2.17版本
> fix: apply natural ordering to policy and attachment listings

- console/src/api/models/link-request.ts
- console/src/views/S3Link.vue
- src/main/java/run/halo/s3os/LinkRequest.java
- src/main/java/run/halo/s3os/S3LinkController.java
- src/main/java/run/halo/s3os/S3LinkService.java
- src/main/java/run/halo/s3os/S3LinkServiceImpl.java
fixes https://github.com/halo-dev/plugin-s3/issues/152
```release-note
S3关联时支持选择加入的分组
```
> feat: support selecting groups to join when link

- src/main/resources/plugin.yaml
将 requires 改动到 2.20.0
目前 Halo 2.20.0 已经发布，此 https://github.com/halo-dev/plugin-s3/pull/167 功能需要在 2.20.0 才能完整工作，因此升级到此版本后准备发版
```release-note
None
```
> chore: update requires to 2.20.0
