- gradle.properties
- src/main/resources/plugin.yaml
> Bump version to 1.2.0

- gradle.properties
- src/main/resources/extensions/policy-template-s3os.yaml
- src/main/resources/plugin.yaml
Fixes https://github.com/halo-sigs/plugin-s3/issues/9
```release-note
fix endpointProtocol setting item does not take effect
```
> fix: EndpointProtocol setting item does not take effect

- build.gradle
- src/main/java/run/halo/s3os/S3OsAttachmentHandler.java
Fixes https://github.com/halo-sigs/plugin-s3/issues/6
```release-note
Use async client and multipart upload to avoid out of memory
```
> perf: Use async client and multipart upload to avoid out of memory

- src/main/java/run/halo/s3os/S3OsAttachmentHandler.java
- src/main/java/run/halo/s3os/S3OsProperties.java
- src/main/resources/extensions/policy-template-s3os.yaml
Fixes https://github.com/halo-sigs/plugin-s3/issues/12
```release-note
add access style options to support minio binding domain names
```
⚠️在发布新版本前在README里增加兼容访问风格相关说明
> feat: add access style options to support minio binding domain names

- src/main/java/run/halo/s3os/S3OsAttachmentHandler.java
Fixes https://github.com/halo-dev/halo/issues/2945
```release-note
Add file check with the same name when uploading
```
我这里使用了ConcurrentHashMap避免**同时**上传两个同名文件导致文件覆盖问题，在本地存储策略中是由操作系统保证的
不知道这样是不是一个好方法
S3AsyncClient中没有`doesObjectExist`类似的方法，官方的文档也让用`headObject`捕获异常的办法来判断文件是否存在，详见https://github.com/aws/aws-sdk-java-v2/blob/master/docs/LaunchChangelog.md 中搜索`doesObjectExist`
> feat: check the file already exists before uploading

- README.md
因为增加了访问风格选项，导致配置比较难理解，因此增加配置指南
```release-note
None
```
> chore: add configuration guide in README

- gradle.properties
- src/main/resources/plugin.yaml
perf: Use async client and multipart upload to avoid out of memory by @longjuan in https://github.com/halo-sigs/plugin-s3/pull/7
feat: add access style options to support minio binding domain names by @longjuan in https://github.com/halo-sigs/plugin-s3/pull/13
feat: check the file already exists before uploading by @longjuan in https://github.com/halo-sigs/plugin-s3/pull/11
```release-note
None
```
> chore: bump version and correct license

- src/main/java/run/halo/s3os/S3OsAttachmentHandler.java
Fixes https://github.com/halo-sigs/plugin-s3/issues/23
```release-note
修复文件上传慢的问题
```
> Use S3Client instead of S3AsyncClient to avoid waiting two seconds for closing 

- src/main/java/run/halo/s3os/S3OsAttachmentHandler.java
Fixes https://github.com/halo-sigs/plugin-s3/issues/37
```release-note
永久链接根据访问风格进行拼接
```
使用Path Style的策略
修改前：
修改后：
> Permalink Adaptation Path Style

- gradle.properties
- src/main/resources/plugin.yaml
> chore: bump version to 1.4.1

- src/main/resources/extensions/policy-template-s3os.yaml
> chore: correct typos

- src/main/java/run/halo/s3os/FilePathUtils.java
- src/main/java/run/halo/s3os/S3LinkServiceImpl.java
- src/main/java/run/halo/s3os/S3OsProperties.java
- src/main/resources/extensions/policy-template-s3os.yaml
Fixes #69 
```release-note
文件上传路径支持使用`${year}`,`${month}`,`${day}`占位符
```
> feat: Time placeholder of upload path

- README.md
> chore: Modify upyun compatibility and service provider document hyperlink format

- console/src/views/HomeView.vue
移除v-permission以避免复选框消失
fixes https://github.com/halo-dev/plugin-s3/issues/82
```release-note
None
```
> fix: remove v-permission to avoid checkbox disappearing

- .github/workflows/workflow.yaml
- build.gradle
1. 支持构建 Console 的内容。
2. 支持创建 Release 之后发布到 Halo 应用市场。
```release-note
None
```
> chore: update github action

- gradle.properties
- src/main/java/run/halo/s3os/UrlUtils.java
- src/test/java/run/halo/s3os/UrlUtilsTest.java
fixes https://github.com/halo-dev/plugin-s3/issues/93
```release-note
修复从旧版本升级后上传文件的NPE错误
```
/kind bug
> Fix findUrlSuffix NPE when upgrading from old version

- src/main/java/run/halo/s3os/S3LinkController.java
```release-note
修复 Halo 2.11 中 关联S3文件 功能报错的问题
```
fixes #102
> fix: list s3 file error in Halo 2.11

- build.gradle
- console/package.json
- console/pnpm-lock.yaml
- console/vite.config.ts
使用 `@halo-dev/ui-plugin-bundler-kit` 简化构建配置。
```release-note
None
```
> chore: simplify bundler config

- gradle.properties
> chore: bump version to 1.8.0

- gradle.properties
> chore: bump version to 1.9.0

- gradle.properties
> chore: bump version to 1.11.0

- console/package.json
- console/pnpm-lock.yaml
- console/src/views/S3Link.vue
- src/main/resources/plugin.yaml
Refactor data list using ⁠VEntityContainer to optimize display across devices of various sizes.
See https://github.com/halo-dev/halo/pull/7383
Note: Updating to this version requires Halo >= 2.21.0.
```release-note
适配 Halo 2.21.0 的数据列表样式
```
> Refactor data list using VEntityContainer
